/**
 * L12 — payment authorization, capture, release and refund.
 *
 * THE PROBLEM THIS MODULE EXISTS TO SOLVE
 *
 * A payment provider will deliver the same callback twice. Not might — will.
 * Networks retry, webhooks replay, an operator resends. Canon's L12-G3 is
 * exactly this: "lost callback replay causes no duplicate financial effect".
 *
 * The defence is not "check whether we have seen this before and skip". That is
 * a race: two replays arriving together both check, both find nothing, and both
 * post. The defence is that every financial effect is keyed by something the
 * PSP gives us and the ledger refuses a second transaction under the same key.
 * Deduplication belongs at the point of record, not at the point of decision.
 *
 * PAYMENT SAYS NOTHING ABOUT THE WORK
 *
 * Canon's first invariant here: "Payment never implies safe/assigned/ready/
 * completed." A captured payment is a fact about money and nothing else. There
 * is deliberately no field on any type below that could be read as work status,
 * and no function that advances one.
 */

import { type Money, money } from "../l6/pricing";
import {
  postTransaction, debit, credit,
  type LedgerTransaction, type LedgerEntry,
} from "./ledger";

export class PaymentInvariantError extends Error {
  constructor(readonly invariant: string, message: string) {
    super(message);
    this.name = "PaymentInvariantError";
  }
}

/**
 * Money the customer has agreed we may take, but which we have not taken.
 *
 * An authorization is a ceiling, never a charge. Canon's L12-G2 turns on the
 * difference: when a job closes for less than was authorized, the unused
 * portion is released rather than quietly kept.
 */
export type PaymentAuthorization = {
  readonly authorizationId: string;
  readonly jobOrderId: string;
  readonly authorized: Money;
  readonly captured: Money;
  readonly released: Money;
  readonly status: "OPEN" | "PARTIALLY_CAPTURED" | "CLOSED";
  readonly authorizedAt: string;
  /** The PSP's own reference. Idempotency is keyed from this, not from ours. */
  readonly pspRef: string;
};

export function authorize(input: {
  authorizationId: string;
  jobOrderId: string;
  amount: Money;
  pspRef: string;
  now: string;
}): PaymentAuthorization {
  if (input.amount.minorUnits <= 0) {
    throw new PaymentInvariantError("EMPTY_AUTHORIZATION", "authorising zero is not an authorisation");
  }
  return Object.freeze({
    authorizationId: input.authorizationId,
    jobOrderId: input.jobOrderId,
    authorized: input.amount,
    captured: money(0, input.amount.currency),
    released: money(0, input.amount.currency),
    status: "OPEN" as const,
    authorizedAt: input.now,
    pspRef: input.pspRef,
  });
}

/** What remains takeable: authorized minus what has been taken or given back. */
export function availableToCapture(auth: PaymentAuthorization): Money {
  return Object.freeze({
    minorUnits: auth.authorized.minorUnits - auth.captured.minorUnits - auth.released.minorUnits,
    currency: auth.authorized.currency,
  });
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/**
 * A financial instruction, keyed so it can only take effect once.
 *
 * `idempotencyKey` is derived from the PSP event, not generated by us. Two
 * deliveries of the same event carry the same key and therefore describe the
 * same effect; the ledger rejects the second because the transaction id is
 * derived from that key.
 */
export type PaymentCommand = {
  readonly idempotencyKey: string;
  readonly kind: "CAPTURE" | "REFUND" | "RELEASE" | "PAYOUT";
  readonly jobOrderId: string;
  readonly amount: Money;
  readonly pspRef: string;
};

export type PaymentEffect = {
  readonly command: PaymentCommand;
  readonly authorization: PaymentAuthorization;
  readonly transaction: LedgerTransaction;
};

/**
 * Take money that was authorized.
 *
 * Capturing more than remains available throws rather than clamping. Clamping
 * would silently succeed with a different amount than the caller asked for,
 * which in a payments system is the worst of both outcomes.
 */
export function capture(input: {
  authorization: PaymentAuthorization;
  amount: Money;
  idempotencyKey: string;
  pspRef: string;
  now: string;
}): PaymentEffect {
  const auth = input.authorization;
  if (auth.status === "CLOSED") {
    throw new PaymentInvariantError("AUTHORIZATION_CLOSED", `authorization ${auth.authorizationId} is closed`);
  }
  const available = availableToCapture(auth);
  if (input.amount.minorUnits > available.minorUnits) {
    throw new PaymentInvariantError(
      "OVER_CAPTURE",
      `cannot capture ${input.amount.minorUnits} against ${available.minorUnits} remaining; ` +
      "an authorisation is a ceiling, not a suggestion",
    );
  }

  const captured = money(auth.captured.minorUnits + input.amount.minorUnits, auth.authorized.currency);
  const next: PaymentAuthorization = Object.freeze({
    ...auth,
    captured,
    status: captured.minorUnits === auth.authorized.minorUnits ? "CLOSED" as const : "PARTIALLY_CAPTURED" as const,
  });

  // Money moves from what the customer owed into what the PSP is holding.
  const entries: LedgerEntry[] = [
    debit("PSP_CLEARING", input.amount, `capture against ${auth.authorizationId}`),
    credit("CUSTOMER_RECEIVABLE", input.amount, "customer paid"),
  ];

  return Object.freeze({
    command: Object.freeze({
      idempotencyKey: input.idempotencyKey, kind: "CAPTURE" as const,
      jobOrderId: auth.jobOrderId, amount: input.amount, pspRef: input.pspRef,
    }),
    authorization: next,
    transaction: postTransaction({
      // Derived from the idempotency key, so a replay collides at the ledger.
      transactionId: `TXN-${input.idempotencyKey}`,
      jobOrderId: auth.jobOrderId,
      kind: "CAPTURE",
      entries,
      postedAt: input.now,
      sourceRef: input.pspRef,
    }),
  });
}

/**
 * Give back what was authorized but not needed — canon's L12-G2.
 *
 * A release is not a refund. Nothing was taken, so nothing comes back; the
 * customer's card simply stops having a hold on it. The ledger still records it
 * because "we stopped being entitled to this" is a real event, and a customer
 * asking why their available balance changed deserves an answer.
 */
export function releaseUnused(input: {
  authorization: PaymentAuthorization;
  idempotencyKey: string;
  pspRef: string;
  now: string;
}): PaymentEffect {
  const auth = input.authorization;
  const unused = availableToCapture(auth);
  if (unused.minorUnits <= 0) {
    throw new PaymentInvariantError(
      "NOTHING_TO_RELEASE",
      `authorization ${auth.authorizationId} has nothing unused to release`,
    );
  }

  const amount = money(unused.minorUnits, auth.authorized.currency);
  const next: PaymentAuthorization = Object.freeze({
    ...auth,
    released: money(auth.released.minorUnits + amount.minorUnits, auth.authorized.currency),
    status: "CLOSED" as const,
  });

  return Object.freeze({
    command: Object.freeze({
      idempotencyKey: input.idempotencyKey, kind: "RELEASE" as const,
      jobOrderId: auth.jobOrderId, amount, pspRef: input.pspRef,
    }),
    authorization: next,
    transaction: postTransaction({
      transactionId: `TXN-${input.idempotencyKey}`,
      jobOrderId: auth.jobOrderId,
      kind: "AUTHORIZATION_RELEASE",
      entries: [
        // The hold is given up: we no longer expect this money, and we were
        // never holding it.
        credit("CUSTOMER_RECEIVABLE", amount, "unused authorisation released"),
        debit("DONEEO_REVENUE", amount, "reversal of expected margin on unperformed work"),
      ],
      postedAt: input.now,
      sourceRef: input.pspRef,
    }),
  });
}

/** Money already captured, going back. Distinct from a release in every way. */
export function refund(input: {
  authorization: PaymentAuthorization;
  amount: Money;
  idempotencyKey: string;
  pspRef: string;
  reason: string;
  now: string;
}): PaymentEffect {
  const auth = input.authorization;
  if (input.amount.minorUnits > auth.captured.minorUnits) {
    throw new PaymentInvariantError(
      "OVER_REFUND",
      `cannot refund ${input.amount.minorUnits} when only ${auth.captured.minorUnits} was captured`,
    );
  }
  if (!input.reason.trim()) {
    throw new PaymentInvariantError("NO_REASON", "a refund without a stated reason is not auditable");
  }

  return Object.freeze({
    command: Object.freeze({
      idempotencyKey: input.idempotencyKey, kind: "REFUND" as const,
      jobOrderId: auth.jobOrderId, amount: input.amount, pspRef: input.pspRef,
    }),
    authorization: Object.freeze({
      ...auth,
      captured: money(auth.captured.minorUnits - input.amount.minorUnits, auth.authorized.currency),
    }),
    transaction: postTransaction({
      transactionId: `TXN-${input.idempotencyKey}`,
      jobOrderId: auth.jobOrderId,
      kind: "REFUND",
      entries: [
        debit("CUSTOMER_RECEIVABLE", input.amount, `refund: ${input.reason}`),
        credit("PSP_CLEARING", input.amount, "money returned to the customer"),
      ],
      postedAt: input.now,
      sourceRef: input.pspRef,
    }),
  });
}

/** Pay the provider what the settlement said they earned. */
export function payout(input: {
  jobOrderId: string;
  amount: Money;
  idempotencyKey: string;
  pspRef: string;
  now: string;
}): LedgerTransaction {
  if (input.amount.minorUnits <= 0) {
    throw new PaymentInvariantError("EMPTY_PAYOUT", "paying out zero is not a payout");
  }
  return postTransaction({
    transactionId: `TXN-${input.idempotencyKey}`,
    jobOrderId: input.jobOrderId,
    kind: "PAYOUT",
    entries: [
      debit("PROVIDER_PAYABLE", input.amount, "provider paid"),
      credit("PSP_CLEARING", input.amount, "funds sent to the provider"),
    ],
    postedAt: input.now,
    sourceRef: input.pspRef,
  });
}

// ---------------------------------------------------------------------------
// Replay protection
// ---------------------------------------------------------------------------

/**
 * The idempotency key for a PSP callback.
 *
 * Built from what the PSP tells us, so two deliveries of one event produce one
 * key. Nothing here uses a timestamp, a counter or a random value — all three
 * would make a replay look new, which is the entire failure mode.
 */
export function callbackKey(input: {
  pspEventId: string;
  jobOrderId: string;
  kind: PaymentCommand["kind"];
}): string {
  return `${input.kind}-${input.jobOrderId}-${input.pspEventId}`;
}

/**
 * Whether this effect has already been recorded.
 *
 * Intended as a cheap pre-check, NOT as the guarantee. The guarantee is that
 * transactionId is derived from the idempotency key and the ledger store
 * enforces uniqueness on it — so two concurrent replays that both pass this
 * check still produce exactly one posting.
 */
export function alreadyApplied(
  posted: readonly LedgerTransaction[],
  idempotencyKey: string,
): boolean {
  return posted.some(t => t.transactionId === `TXN-${idempotencyKey}`);
}
