/**
 * The 23 canonical layers, generated from the corrected architecture.
 *
 * DO NOT EDIT BY HAND. Regenerate with arch/gen_arch_code.py so that the
 * document, the boards and this file cannot disagree.
 *
 * `modules` is the claim that a layer is implemented by real files.
 * tests/architecture-conformance.test.ts asserts every path exists, so a
 * deleted or renamed module fails the suite instead of rotting silently.
 */

export type LayerId =
  "L1" | "L2" | "L3" | "L4" | "L5" | "L6" | "L7" | "L8" | "L09A" | "L09B" | "L10" | "L11" | "L12" | "L13" | "P1" | "P2" | "P3" | "P4" | "P5" | "P6" | "P7" | "P8" | "P9";

export type LayerStatus = "IMPLEMENTED" | "PARTIAL" | "PLANNED";

export type Layer = {
  id: LayerId;
  title: string;
  kind: "domain" | "platform";
  status: LayerStatus;
  /** Repo-relative paths implementing this layer. Empty when PLANNED. */
  modules: readonly string[];
  /** Authoritative artifacts this layer owns. Exactly one owner each. */
  owns: readonly string[];
  /** Explicit disclaimers. Each points at another layer that does own it. */
  doesNotOwn: readonly string[];
  /** Invariants that hold for this layer and may not be traded away. */
  invariants: readonly string[];
};

export const LAYERS: Record<LayerId, Layer> = {
  L1: {
    id: "L1",
    title: "Intake, Context & WorkCase",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/work-case.ts",
      "lib/application/work-case-service.ts",
      "lib/application/work-case-store.ts",
      "lib/application/d1-work-case-store.ts",
    ],
    owns: [
      "WorkCase creation and identity",
      "Original request and normalized intake",
      "Customer goal / desired outcome",
      "Context capture: location, timing, access, recipients",
      "Initial evidence and attachment references",
      "Continuity link to future JobOrders/branches",
    ],
    doesNotOwn: [
      "Task architecture or RequirementContract",
      "Provider selection or availability",
      "Safety/legal final decisions",
      "Pricing or payment",
      "Execution control",
      "Outcome verification",
    ],
    invariants: [
      "No plan/estimate/match before Layer 2",
      "Original customer input remains immutable source evidence",
      "WorkCase is continuity container; JobOrder is not created here",
    ],
  },
  L2: {
    id: "L2",
    title: "Intelligence & Planning",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/planner.ts",
      "lib/job-intelligence.ts",
      "lib/work-ontology.ts",
      "lib/household-catalog.ts",
      "lib/intelligence-task-identity.ts",
      "lib/requirement-contract.ts",
      "lib/application/requirement-contract-service.ts",
      "lib/application/requirement-contract-store.ts",
      "lib/application/d1-requirement-contract-store.ts",
      "lib/application/requirement-contract-projection.ts",
      "lib/application/requirement-contract-hashing.ts",
    ],
    owns: [
      "Problem understanding",
      "Task decomposition",
      "Global pre-analysis",
      "Fact resolution",
      "MSI and question strategy",
      "TaskGraph architecture",
      "Abstract resource planning",
      "Time/route/cost estimation",
      "CompletionSpecification",
      "Architecture simulation",
      "RequirementContract compilation",
    ],
    doesNotOwn: [
      "Provider matching/availability",
      "Commercial offer/pricing",
      "Final rule authority",
      "Payment/settlement",
      "Execution truth/outcome",
    ],
    invariants: [
      "Plan before supply",
      "Use AI for meaning; code for authority",
      "Ask only material questions; never repeat known facts",
      "Full reanalysis only when affected scope cannot be isolated",
    ],
  },
  L3: {
    id: "L3",
    title: "Trust, Safety, Rules & Compliance",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/rules-gate.ts",
    ],
    owns: [
      "Rule applicability",
      "Risk/regulatory classification",
      "Qualification/control requirements",
      "Provider eligibility rules",
      "Dynamic risk reassessment",
      "Safety holds",
      "Policy exceptions and manual review",
    ],
    doesNotOwn: [
      "Task planning",
      "Provider ranking beyond eligibility",
      "Pricing",
      "Payment capture",
      "Execution state",
      "Outcome truth",
    ],
    invariants: [
      "Hard legal/safety constraints cannot be outvoted by optimization",
      "Eligibility at offer time does not imply dispatch readiness",
      "Payment never implies safety clearance",
    ],
  },
  L4: {
    id: "L4",
    title: "Fulfillment, Matching & Team Assembly",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/work-orders.ts",
    ],
    owns: [
      "Candidate retrieval",
      "Hard eligibility filtering",
      "Team assembly and roles",
      "Availability and capacity",
      "Provider/resource feasibility",
      "Scheduling/routing coordination",
      "FulfillmentSimulation",
      "Feasible option ranking",
      "FulfillmentCostSnapshot",
    ],
    doesNotOwn: [
      "What work is required",
      "Safety/rule definition",
      "Customer price",
      "Customer commitment/payment",
      "Execution truth",
      "Final settlement",
    ],
    invariants: [
      "RequirementContract is authoritative for hard constraints",
      "Bookable feasibility precedes customer offer",
      "Provider acceptance occurs after customer authorization unless category policy requires otherwise",
    ],
  },
  L5: {
    id: "L5",
    title: "Resources, Rentals, Logistics & Partners",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "Resource inventory/compatibility",
      "True-gap calculation",
      "Rental/purchase/partner sourcing",
      "Reservation",
      "Pickup/delivery/return coordination",
      "Resource readiness and receipts",
    ],
    doesNotOwn: [
      "Task requirements",
      "Provider/team matching",
      "Customer pricing",
      "Cancellation responsibility",
      "Execution of task itself",
      "Settlement authority",
    ],
    invariants: [
      "Check customer -> provider/team -> partner/rental/purchase",
      "Rental pickup/return is not working time unless policy explicitly says otherwise",
      "No arbitrary executor-added resource charge",
    ],
  },
  L6: {
    id: "L6",
    title: "CommercialOffer & Pricing",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "Pricing strategy/policy",
      "Cost composition",
      "Scenario pricing",
      "Tax determination interface",
      "ScopeContract",
      "Commercial validity/expiry",
      "Payment topology policy selection",
    ],
    doesNotOwn: [
      "Provider eligibility",
      "Customer authorization/capture",
      "Cancellation reconciliation",
      "Outcome truth",
      "Final customer charge/provider payable",
      "Ledger",
    ],
    invariants: [
      "Customer sees feasible options only",
      "Offer is based on known facts and stated assumptions",
      "Offer price is not final settlement after reality changes",
    ],
  },
  L7: {
    id: "L7",
    title: "Commitment, Capacity, Rescheduling & Cancellation Architecture",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/layers/l7/commitment.ts",
      "lib/layers/l7/cancellation.ts",
      "lib/application/commitment-service.ts",
      "lib/application/commitment-store.ts",
      "lib/application/d1-commitment-store.ts",
    ],
    owns: [
      "Customer commitment state",
      "Provider acceptance state",
      "CapacityReservation per assigned role/person/resource",
      "PreparationRecord",
      "CommitmentSnapshot",
      "Reschedule strategy",
      "Capacity recovery/backfill",
      "Cancellation request and reconciliation",
    ],
    doesNotOwn: [
      "Price calculation (L6)",
      "Final customer charge/provider payable/ledger (L12)",
      "Responsibility adjudication (09B)",
      "Execution truth (L10)",
      "Claims/disputes (L13)",
    ],
    invariants: [
      "No universal cancellation hours/percentages are canonical.",
      "Cancellation remains requestable.",
      "Voluntary cancellation ≠ Field Reality Block.",
      "ProtectedProviderPayable and customer liability are different quantities.",
      "Net Lost Reserved Capacity = Reserved Capacity − Successfully Reallocated Capacity.",
      "Customer never automatically pays full original price for unperformed work.",
    ],
  },
  L8: {
    id: "L8",
    title: "Execution Preparation, Preflight & Dispatch Architecture",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "MissionPackage compilation",
      "Role-scoped executor briefing",
      "Team coordination",
      "Resource/material/rental readiness",
      "Access/recipient readiness",
      "T3 eligibility invocation",
      "Dispatch readiness",
      "En-route handoff",
    ],
    doesNotOwn: [
      "Live execution (L10)",
      "Requirement architecture (L2)",
      "Safety/rule authority (L3)",
      "Pricing (L6)",
      "Final settlement (L12)",
      "Outcome verification (L11)",
    ],
    invariants: [
      "Provider acceptance ≠ dispatch readiness.",
      "Payment authorization ≠ dispatch readiness.",
      "L8 ends at ExecutionReady/Dispatch; L10 owns live execution.",
      "Arrival Reality Check is separate from pre-departure preflight.",
    ],
  },
  L09A: {
    id: "L09A",
    title: "Reality & Recovery Decision Architecture",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/layers/l09a/reality.ts",
      "lib/layers/l09a/recovery.ts",
      "lib/application/reality-service.ts",
      "lib/application/reality-store.ts",
      "lib/application/d1-reality-store.ts",
    ],
    owns: [
      "RealityCase",
      "Field evidence + Field MSI",
      "FactLedger field updates",
      "Semantic R0–R5 impact classification",
      "Dependency impact analysis",
      "Safety interrupt routing",
      "Fastest-safe-solution hierarchy",
      "Targeted reanalysis coordination",
      "Resume/branch/partial-close decision",
    ],
    doesNotOwn: [
      "Responsibility/economic allocation (09B)",
      "Pricing revised work (L6)",
      "Final cancellation settlement (L7/L12)",
      "Final outcome truth (L11)",
    ],
    invariants: [
      "R0–R5 are semantic classes, NOT severity.",
      "Physical reality is authoritative but cannot bypass controls.",
      "Solution before broad replanning.",
      "Continue unaffected TaskBlocks when dependencies/safety allow.",
      "Full replan and cancellation are last resort.",
    ],
  },
  L09B: {
    id: "L09B",
    title: "Responsibility & Fairness Economic Architecture",
    kind: "domain",
    status: "PARTIAL",
    modules: [
      "lib/layers/l09b/responsibility.ts",
      "lib/layers/l09b/allocation.ts",
      "lib/application/settlement-service.ts",
    ],
    owns: [
      "Causality classification",
      "Customer/provider/Doneeo/external responsibility tests",
      "Capacity-loss input after recovery",
      "ProtectedProviderPayable",
      "CustomerRealityAdjustment",
      "DoneeoAbsorption / RecoveryCredit",
      "AdjustmentInstruction",
      "Responsibility DecisionTrace",
    ],
    doesNotOwn: [
      "Weighted blame scoring",
      "Pricing new work (L6)",
      "Final capture/refund/ledger (L12)",
      "Claims appeal adjudication (L13)",
      "Safety authority (L3)",
    ],
    invariants: [
      "NO weighted blame engine.",
      "PPP ≠ customer liability ≠ Doneeo absorption.",
      "Doneeo planning error does not become customer surcharge.",
      "Hidden condition alone does not create customer liability.",
      "Customer declining revised work does not make revised job/full original price automatically owed.",
    ],
  },
  L10: {
    id: "L10",
    title: "Live Execution & Change Control",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "Execution state machine",
      "TaskBlock progression",
      "Milestones/checkpoints",
      "ExecutionJournal",
      "Live timing/ETA",
      "Handoffs",
      "Issue/change detection",
      "Approved adaptation application",
      "Completion submission",
    ],
    doesNotOwn: [
      "Requirement architecture",
      "Responsibility allocation",
      "Final outcome verification",
      "Pricing/settlement",
      "Claims",
    ],
    invariants: [
      "Execution never self-expands scope",
      "Journal append-only",
      "Actuals are evidence, not automatically customer charges",
      "Continue unaffected work where safe",
    ],
  },
  L11: {
    id: "L11",
    title: "Outcome, Completion & Evidence Architecture",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "Completion submission validation",
      "CompletionSpecification verification",
      "Evidence integrity",
      "TaskBlockCompletionDecision",
      "JobOrderCompletionDecision",
      "VerifiedActuals",
      "OutcomeRecord",
      "Actual-vs-estimate variance report",
    ],
    doesNotOwn: [
      "Customer charge/provider payable",
      "Responsibility allocation",
      "Claims adjudication",
      "New planning except explicit remediation/reality callbacks",
    ],
    invariants: [
      "CompletionSpecification is the central success authority.",
      "Customer acceptance is evidence, not sole authority.",
      "Done/Submit ≠ Completed.",
      "Blocked execution is not automatically a terminal outcome.",
      "Cancelled is final only when L7 finalizes cancellation.",
      "JobOrder closure ≠ WorkCase closure.",
      "Actual cost facts are not automatically customer charges.",
    ],
  },
  L12: {
    id: "L12",
    title: "Settlement, Ledger, Reconciliation & FinanceOps",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "Final settlement calculation",
      "Payment capture/release/refund coordination",
      "Provider payable",
      "Tax settlement references",
      "Append-only double-entry ledger",
      "Reconciliation",
      "FinanceOps exceptions/holds/retries/reversals",
    ],
    doesNotOwn: [
      "Work planning",
      "Safety qualification",
      "Outcome truth",
      "Claims physical truth",
      "Editable balances/history",
    ],
    invariants: [
      "Payment never implies safe/assigned/ready/completed.",
      "Customer charge ≠ provider payable.",
      "FinanceOps cannot rewrite physical truth or ledger history.",
      "No direct DB edits.",
      "Doneeo/partner share absorbs platform/partner responsibility and Recovery Credits without silently shifting it to customer or executor.",
      "Append-only balanced postings; idempotent PSP commands; transactional inbox/outbox; reconciliation; FinanceOps exceptions; no direct balance edits.",
    ],
  },
  L13: {
    id: "L13",
    title: "Branch, Continuity, Claims & Support Architecture",
    kind: "domain",
    status: "PLANNED",
    modules: [],
    owns: [
      "BranchRelationship",
      "Prerequisite/follow-up/remediation/warranty/incident/customer-added branches",
      "CandidateFollowUp conversion",
      "WorkCase continuity",
      "Claims/disputes/support cases",
      "Remedies/appeals",
    ],
    doesNotOwn: [
      "Rewriting OutcomeRecord (L11)",
      "Rewriting ledger balances/history (L12)",
      "Provider eligibility (L3/L4)",
      "Pricing (L6)",
      "Original requirement truth",
    ],
    invariants: [
      "WorkCase may outlive a JobOrder.",
      "Branch types: PREREQUISITE_FOR, FOLLOW_UP_TO, REMEDIATION_FOR, CUSTOMER_ADDED_SCOPE, INCIDENT_RECOVERY, WARRANTY_REWORK.",
      "Independent observed work never becomes current billable scope without consent.",
      "Claims/support consume source truth; they do not rewrite it.",
    ],
  },
  P1: {
    id: "P1",
    title: "Platform Orchestrator, Workflow & State Control",
    kind: "platform",
    status: "PARTIAL",
    modules: [
      "lib/application/d1-intelligence-control-service.ts",
    ],
    owns: [
      "Workflow coordination",
      "State transition guards",
      "Command routing",
      "Event orchestration",
      "Version lineage",
      "Sagas/compensation",
      "Idempotency/concurrency",
      "Human-review routing",
    ],
    doesNotOwn: [
      "Planning/safety/pricing/fulfillment/outcome domain decisions",
      "Direct ledger edits",
      "Arbitrary cross-domain writes",
    ],
    invariants: [
      "Orchestrator coordinates; domains decide",
      "No God Object",
      "Design for failure",
      "Commands and events are distinct",
    ],
  },
  P2: {
    id: "P2",
    title: "Data, FactLedger, Evidence & DecisionTrace Architecture",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Logical data ownership map",
      "FactLedger provenance",
      "Evidence/object references",
      "DecisionTrace",
      "Validity/expiry metadata",
      "Transactional inbox/outbox/event log persistence",
      "Derived read/search/warehouse projections",
    ],
    doesNotOwn: [
      "Business decisions",
      "Event transport/backbone (P6)",
      "One giant cross-domain mutable record",
      "External-system truth",
    ],
    invariants: [
      "No giant JobOrder JSON.",
      "FactLedger does not mean all domain tables collapse into one store.",
      "Derived read/search/warehouse never outranks source.",
      "DecisionTrace is first-class.",
      "Validity/expiry is first-class.",
      "P6 owns event transport, not P2.",
    ],
  },
  P3: {
    id: "P3",
    title: "Identity, Consent & Access",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Customer/executor identities",
      "Organizations",
      "Roles/permissions",
      "Third-party recipient authorization",
      "Consent records",
      "Session/security context",
      "Visibility/privacy policies",
    ],
    doesNotOwn: [
      "Job planning",
      "Provider eligibility",
      "Pricing",
      "Claims truth",
      "Financial settlement",
    ],
    invariants: [
      "Third-party recipients see only relevant information unless explicitly granted more",
      "Internal operators use role-scoped access",
      "Advertisers/partners never receive conversation/workcase data outside authorized service purpose",
    ],
  },
  P4: {
    id: "P4",
    title: "Platform Security, Fraud/Abuse & Trust Enforcement Architecture",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Platform threat/risk signals",
      "Fraud/abuse detection",
      "Account/device/session protective controls",
      "Transaction risk signals",
      "Runtime security enforcement",
      "Security incidents",
      "Cross-layer security holds",
    ],
    doesNotOwn: [
      "Job-specific regulatory/rule/qualification authority (L3)",
      "Identity/AuthN/AuthZ ownership (P3)",
      "Privacy governance/DSR/retention (P8)",
      "Commercial/settlement decisions",
    ],
    invariants: [
      "L3 owns job safety/legal/qualification decisions.",
      "P4 owns platform security/fraud/abuse/runtime protection.",
      "P3 owns identity/access.",
      "P8 owns privacy compliance.",
    ],
  },
  P5: {
    id: "P5",
    title: "Integrations, Connectors & External Services",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Provide controlled connectivity to external systems",
      "Normalize, validate and translate external data",
      "Manage API integrations, webhooks and connectors",
      "Ensure security, reliability and resilience",
      "Monitor health, performance and usage",
      "Enforce data mapping, governance and compliance",
      "Enable extensibility and ecosystem growth",
      "Expose and consume APIs securely",
      "Transform data to Doneeo canonical models",
      "Manage authentication and authorization",
      "Handle webhooks, callbacks and event subscriptions",
      "Provide connector SDKs and integration patterns",
      "Ensure retries, idempotency and error handling",
      "Monitor and alert on integration health",
      "Version and govern external contracts",
    ],
    doesNotOwn: [
      "Business logic or decisions (the domain layers L2-L11)",
      "Data storage or ledger (P2)",
      "Identity or access (P3)",
      "Security enforcement (P4)",
      "Orchestration or state (P1)",
      "Financial settlement (L12 (Settlement, Ledger & Reconciliation))",
    ],
    invariants: [
      "Standardized — use open standards and contracts",
      "Observable — monitor, log and trace",
      "Secure by Default — AuthN, AuthZ, encryption",
      "Governed — approved, versioned, audited",
      "Resilient & Reliable — retries, timeouts, fallbacks",
      "Extensible — easy to plug and scale",
      "Loose Coupling — async first, event-driven",
      "Data Quality — validate, map, reconcile",
      "P5 writes immutable integration facts to P2",
    ],
  },
  P6: {
    id: "P6",
    title: "Event Backbone, Model Gateway, Observability & 1M-Job Scale Architecture",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Event/message backbone",
      "Worker pools",
      "Model Gateway",
      "Telemetry/observability",
      "Caches/read infrastructure",
      "Reliability patterns",
      "Regional scaling/deployment evolution",
    ],
    doesNotOwn: [
      "Business decisions",
      "Rule authority",
      "Primary domain storage",
      "Identity/security policy",
      "Final financial truth",
    ],
    invariants: [
      "AI reasons/recommends; deterministic code/rules/state/versioning are authority.",
      "No mandatory multi-model consensus.",
      "Learning may propose, never auto-publish compliance rules.",
      "Scale changes HOW, not WHAT.",
      "Million-job logical architecture now; million-job physical infrastructure when load requires it.",
    ],
  },
  P7: {
    id: "P7",
    title: "Notifications, Messaging & User Engagement",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Deliver timely, relevant and actionable messages",
      "Engage users across the journey",
      "Support transactional and conversational messaging",
      "Personalize by context, role and preference",
      "Ensure reliability, delivery and compliance",
      "Provide user communication preferences",
      "Measure engagement and message effectiveness",
      "Route messages to the right channel",
      "Personalize content by context and profile",
      "Trigger messages from events and workflows",
      "Support two-way conversations",
      "Manage templates, localization and rendering",
      "Handle delivery, retries and fallbacks",
      "Track delivery, opens, clicks and replies",
      "Support escalation and urgent alerts",
    ],
    doesNotOwn: [
      "Business or orchestration decisions (the domain layers L1-L11)",
      "Data storage or identity (P2 (Data & FactLedger) and P3 (Identity))",
      "Security enforcement (P4)",
      "Financial transactions (L12 (Settlement, Ledger & Reconciliation))",
      "State or truth (P2) or orchestration (P1)",
    ],
    invariants: [
      "Relevant — context-aware messages",
      "Timely — right time, not too much",
      "Personalized — user, role and context",
      "Actionable — clear call to action",
      "Reliable — deliver or retry",
      "Respectful — user preferences first",
      "Two-Way — listen and respond",
      "Inclusive — accessible and localized",
      "Compliant — legal and policy aligned",
      "Measurable — track and improve",
      "P7 writes communication facts to P2",
    ],
  },
  P8: {
    id: "P8",
    title: "Privacy, Data Governance & Regulatory Compliance Architecture",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Privacy policy",
      "Data classification/handling rules",
      "Privacy impact assessments/DPIA",
      "Data subject rights",
      "Retention/legal hold/disposal",
      "Records of processing",
      "Privacy compliance assurance",
    ],
    doesNotOwn: [
      "Authentication/authorization/session identity (P3)",
      "Runtime security/fraud enforcement (P4)",
      "Primary data storage (P2)",
      "Business decisions",
      "Financial settlement",
    ],
    invariants: [
      "P3 owns identity/access/consent grants; P8 owns privacy policy and data lifecycle.",
      "P4 owns runtime security enforcement.",
      "P2 owns authoritative data/evidence stores.",
      "Privacy controls apply across all domain layers.",
    ],
  },
  P9: {
    id: "P9",
    title: "Payment Rails, Tax/Financial Adapters & Treasury Integrations Architecture",
    kind: "platform",
    status: "PLANNED",
    modules: [],
    owns: [
      "Payment-method token/reference boundary",
      "PSP authorization/capture/refund/void adapter calls",
      "Payout/bank transfer rails",
      "Tax-provider/remittance adapters",
      "FX/provider adapters",
      "Financial webhook normalization",
      "Rail-level retries/idempotency/status",
    ],
    doesNotOwn: [
      "Pricing/fees/customer offer (L6)",
      "Final settlement allocation/customer charge/provider payable (L12/09B)",
      "Authoritative ledger/reconciliation (L12)",
      "Fraud/security policy (P4)",
      "Generic connector framework (P5)",
    ],
    invariants: [
      "L6 owns price; P9 does not.",
      "09B owns responsibility allocation; P9 does not.",
      "L12 owns final settlement, ledger and reconciliation; P9 only executes external rail commands and returns evidence.",
      "P5 owns generic connector framework; P9 owns financial-domain adapter semantics.",
    ],
  },
};

export const LAYER_IDS = Object.keys(LAYERS) as LayerId[];

export function layersImplementing(path: string): Layer[] {
  return LAYER_IDS.map(id => LAYERS[id]).filter(l => l.modules.includes(path));
}
